# Generated by Django 2.0.3 on 2019-02-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('metric', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
    ]
