# Generated by Django 2.0.3 on 2019-02-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('location', 'metric', 'value', 'year', 'month')},
        ),
    ]
