# Generated by Django 2.0.3 on 2019-02-28 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190228_1430'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('location', 'metric', 'year', 'month')},
        ),
    ]
