# Generated by Django 2.0.3 on 2019-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190228_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
